### ISSUE TITLE
Possible to turn this into an addon?

### ISSUE THREAD

**Issue by finalbillybong** [mylesagray/boilerjuice-tank-api#35]
Is it possible to turn this image into a Home Assistant addon? I've had a go myself but am finding it exceedingly difficult on a count of being a dumbass.....

**Comment by mylesagray** [comment]
No plans, I don't use home assistant (homebridge user) but it should be simple enough to run this outside HA and scrape the API.

**Comment by finalbillybong** [comment]
OK thanks. Yes I am running it currently on a ubuntu VM on my Freenas box. I was looking to move it over to my NUC that runs HA. I have a raspi that I could install it on though.
