### ISSUE TITLE
Percent is always 0

### ISSUE THREAD

**Issue by gr4z** [mylesagray/boilerjuice-tank-api#54]
Recently my percent figure is always 0%. Have recreated the image but can't see any errors in the logs, any ideas?

**Comment by mylesagray** [comment]
@gr4z - are you running the latest image? If not, can you - as there were some changes made to the web scraper to address issues similar to this.

**Comment by gr4z** [comment]
Hi, just repulled the latest image and it remains at 0%, output:
`{"capacity":"1100","litres":700.0,"percent":"0"}`

**Comment by mylesagray** [comment]
Fixed in 5e9f369 - container building, should be in the repo in about an hour!

**Comment by gr4z** [comment]
Fixed - thanks!
